# Generated by Django 2.2.5 on 2019-09-26 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='<br/><a href="../password/">Password change form</a>', max_length=255, unique=True, verbose_name='email address')),
                ('passwd', models.CharField(max_length=150, verbose_name='password')),
                ('passwd_exp', models.DateTimeField(blank=True, null=True, verbose_name='password expiration')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('org_admin', models.BooleanField(default=False, verbose_name='org. admin')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='name')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('members_limit', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='members limit')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='jtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join time'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Member'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='key')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='units.Member')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('acc_act', 'account activation'), ('acc_rm', 'account removal'), ('pwd_rst', 'password reset')], db_index=True, max_length=16, verbose_name='type')),
                ('code', models.CharField(db_index=True, max_length=256, verbose_name='code')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Member')),
            ],
            options={
                'verbose_name': 'Member code',
                'verbose_name_plural': 'Member codes',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Organization'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Organization'),
        ),
    ]
