# Generated by Django 2.2.5 on 2019-10-03 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20190925_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='jtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join time'),
        ),
    ]
