# Generated by Django 2.2.5 on 2019-10-04 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_member_jtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercode',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
