# Generated by Django 2.2.7 on 2019-11-06 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20191004_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('release', models.CharField(db_index=True, max_length=64, verbose_name='release')),
                ('uid', models.CharField(db_index=True, max_length=64, verbose_name='UID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Organization')),
            ],
            options={
                'verbose_name': 'Release UID',
                'verbose_name_plural': 'Release UIDs',
                'abstract': False,
            },
        ),
    ]
