# Generated by Django 2.2.7 on 2019-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_releaseuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Organization group',
                'verbose_name_plural': 'Organization groups',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='releaseuid',
            name='url',
            field=models.URLField(default='', max_length=256, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='groups',
            field=models.ManyToManyField(blank=True, to='units.OrganizationGroup'),
        ),
    ]
