# Generated by Django 2.2.7 on 2019-11-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_auto_20191112_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='groups',
            new_name='organization_groups',
        ),
    ]
