# Generated by Django 2.2.7 on 2019-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20191112_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseuid',
            name='unreal_ver',
            field=models.CharField(default='', max_length=32, verbose_name='unreal version'),
        ),
    ]
