# Generated by Django 2.2.7 on 2019-11-14 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_releaseuid_unreal_ver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('unreal_ver', models.CharField(db_index=True, max_length=32, verbose_name='unreal version')),
                ('release_ver', models.CharField(db_index=True, max_length=32, verbose_name='release version')),
                ('changes', models.CharField(max_length=512, verbose_name='changes')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='releaseuid',
            name='unreal_ver',
        ),
        migrations.RemoveField(
            model_name='releaseuid',
            name='release',
        ),
    ]
