# Generated by Django 2.2.7 on 2019-11-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_releaseuid_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseuid',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='releaseuid',
            name='release',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
        migrations.DeleteModel(
            name='ReleaseUID',
        ),
    ]
