# Generated by Django 2.2.5 on 2019-09-18 06:20

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('type', models.CharField(choices=[('Action', 'Action'), ('Condition', 'Condition'), ('Custom', 'Custom'), ('Delay', 'Delay'), ('DialogueLine', 'DialogueLine'), ('End', 'End'), ('Event', 'Event'), ('Fact', 'Fact'), ('Objective', 'Objective'), ('Option', 'Option'), ('Reroute', 'Reroute'), ('Sound', 'Sound'), ('Start', 'Start'), ('Story', 'Story'), ('TimeoutOption', 'TimeoutOption'), ('Trigger', 'Trigger')], db_index=True, max_length=16, verbose_name='type')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('nid', models.CharField(db_index=True, max_length=128, verbose_name='node ID')),
                ('description', models.CharField(default='', max_length=512, verbose_name='description')),
                ('pos_x', models.IntegerField(verbose_name='x position')),
                ('pos_y', models.IntegerField(verbose_name='y position')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('trigger_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('output_pins', models.PositiveSmallIntegerField(default=1, verbose_name='output pins number')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='node meta')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=512, verbose_name='filename')),
                ('ctime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='creation time')),
                ('mtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='modification time')),
                ('story_name', models.CharField(db_index=True, max_length=128, verbose_name='story name')),
                ('uasset_ver', models.CharField(max_length=16, verbose_name='UAsset version')),
                ('story_ver', models.CharField(max_length=16, verbose_name='Story version')),
                ('json_ver', models.CharField(max_length=16, verbose_name='JSON version')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Team')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEntity', 'entity'), ('NFact', 'fact'), ('NObjective', 'objective'), ('NStory', 'story'), ('SoundCue', 'sound cue')], db_index=True, max_length=16, verbose_name='type')),
                ('name', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='name')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
            ],
            options={
                'verbose_name': 'Package asset',
                'verbose_name_plural': 'Package assets',
                'abstract': False,
                'unique_together': {('package', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PackageHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Comment', 'Comment'), ('Image', 'Image'), ('Sequence', 'Sequence'), ('StickyNote', 'StickyNote'), ('Union', 'Union')], db_index=True, max_length=16, verbose_name='type')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='name')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('pos_x', models.IntegerField(verbose_name='x position')),
                ('pos_y', models.IntegerField(verbose_name='y position')),
                ('size_x', models.PositiveIntegerField(verbose_name='x size')),
                ('size_y', models.PositiveIntegerField(verbose_name='y size')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='node meta')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
            ],
            options={
                'verbose_name': 'Package helper',
                'verbose_name_plural': 'Package helper',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageHelperNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_node', to='api.Node')),
                ('package_helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PackageHelper')),
            ],
            options={
                'verbose_name': 'Package helper node',
                'verbose_name_plural': 'Package helper nodes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageEntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PackageEntityType')),
            ],
            options={
                'verbose_name': 'Package entity type',
                'verbose_name_plural': 'Package entity types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageAssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
                ('package_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PackageAsset')),
                ('package_entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PackageEntityType')),
            ],
            options={
                'verbose_name': 'Package asset type',
                'verbose_name_plural': 'Package asset types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='parameters')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
            ],
            options={
                'verbose_name': 'Package action',
                'verbose_name_plural': 'Package actions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inp', 'input'), ('out', 'output')], max_length=8, verbose_name='type')),
                ('index', models.PositiveSmallIntegerField(db_index=True, verbose_name='index')),
                ('my_pin_index', models.PositiveSmallIntegerField(verbose_name='my pin index')),
                ('other_pin_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='other pin index')),
                ('linked_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_node', to='api.Node')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
            ],
            options={
                'verbose_name': 'Node link',
                'verbose_name_plural': 'Node links',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_index', models.PositiveSmallIntegerField(db_index=True, verbose_name='class index')),
                ('name_index', models.PositiveSmallIntegerField(db_index=True, verbose_name='name index')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Node')),
                ('package_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PackageAsset')),
            ],
            options={
                'verbose_name': 'Node asset',
                'verbose_name_plural': 'Node assets',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Package'),
        ),
    ]
