# Generated by Django 2.2.5 on 2019-09-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('units', '0002_auto_20190925_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Member'),
        ),
    ]
