# Generated by Django 2.2.5 on 2019-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190926_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('Action', 'Action'), ('Choice', 'Choice'), ('ChoiceTimeout', 'ChoiceTimeout'), ('Condition', 'Condition'), ('Custom', 'Custom'), ('Delay', 'Delay'), ('DialogueLine', 'DialogueLine'), ('End', 'End'), ('Event', 'Event'), ('Fact', 'Fact'), ('Objective', 'Objective'), ('Reroute', 'Reroute'), ('Sound', 'Sound'), ('Start', 'Start'), ('Story', 'Story'), ('Trigger', 'Trigger')], db_index=True, max_length=16, verbose_name='type'),
        ),
    ]
