# Generated by Django 2.2.5 on 2019-10-02 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20190925_0735'),
        ('api', '0003_auto_20190930_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='locked_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='locked at'),
        ),
        migrations.AddField(
            model_name='package',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_packages', to='units.Member'),
        ),
    ]
