# Generated by Django 2.2.7 on 2019-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191002_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='input_pins',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='input pins number'),
        ),
    ]
