# Generated by Django 2.2.7 on 2019-11-15 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_auto_20191115_1048'),
        ('api', '0005_node_input_pins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('unreal_ver', models.CharField(db_index=True, max_length=32, verbose_name='unreal version')),
                ('release_ver', models.CharField(db_index=True, max_length=32, verbose_name='release version')),
                ('changes', models.CharField(max_length=512, verbose_name='changes')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('uid', models.CharField(db_index=True, max_length=64, verbose_name='UID')),
                ('url', models.URLField(default='', max_length=256, verbose_name='URL')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Organization')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Release')),
            ],
            options={
                'verbose_name': 'Release UID',
                'verbose_name_plural': 'Release UIDs',
                'abstract': False,
            },
        ),
    ]
