# Generated by Django 2.2.7 on 2019-11-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_release_releaseuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='weight'),
        ),
    ]
