# Generated by Django 2.2.7 on 2019-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_node_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageasset',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='is enabled'),
        ),
        migrations.AlterField(
            model_name='node',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
    ]
