# Generated by Django 2.2.8 on 2019-12-06 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191128_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehelper',
            name='hid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=128, verbose_name='helper ID'),
        ),
    ]
